# Generated by Django 2.1a1 on 2018-05-19 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailEventLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('raw_data', models.TextField()),
            ],
            options={
                'ordering': ('-last_modified', '-created'),
                'abstract': False,
            },
        ),
    ]
