# Generated by Django 2.0.5 on 2018-07-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maileventlogmodel',
            options={'ordering': ('created', '-last_modified')},
        ),
    ]
