# Generated by Django 2.1b1 on 2018-07-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created', '-last_modified'), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('created', '-last_modified')},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pinned_order', 'created', '-last_modified')},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('created', '-last_modified'), 'verbose_name_plural': 'topics'},
        ),
        migrations.AddField(
            model_name='post',
            name='pinned_order',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
