# Generated by Django 2.0.5 on 2018-07-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180706_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='id',
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
