# Generated by Django 2.1rc1 on 2018-08-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created', 'last_modified'), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('created', 'last_modified')},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pinned_order', '-created', '-last_modified')},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('created', 'last_modified'), 'verbose_name_plural': 'topics'},
        ),
    ]
