# Generated by Django 2.1rc1 on 2018-08-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='identifier',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
