# Generated by Django 2.1 on 2018-08-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20180805_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='id',
        ),
        migrations.AlterField(
            model_name='feature',
            name='identifier',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
