# Generated by Django 2.0 on 2018-01-10 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import melody.posts.renderer
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('post', ('-last_modified', '-created')),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('in_reply_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='posts.Post')),
            ],
            options={
                'ordering': ('in_reply_to', '-last_modified', '-created'),
            },
            bases=(models.Model, melody.posts.renderer.Renderable),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'topics',
                'ordering': ('-last_modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.Topic')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('parent', '-last_modified', '-created'),
                'abstract': False,
            },
            bases=('posts.topic',),
        ),
        migrations.AddField(
            model_name='topic',
            name='posts',
            field=models.ManyToManyField(blank=True, editable=False, related_name='topics', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='history',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='posts.Post'),
        ),
    ]
