# Generated by Django 2.0 on 2017-12-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
