# Generated by Django 2.0 on 2017-12-28 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import melody.core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                (
                    'author',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(melody.core.models.CreateUpdateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
            bases=(melody.core.models.CreateUpdateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'topic_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='posts.Topic'
                    )
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='posts.Category'
                    )
                ),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
            bases=('posts.topic',),
        ),
        migrations.AddField(
            model_name='topic',
            name='posts',
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name='categories',
                to='posts.Post'
            ),
        ),
    ]
