# Generated by Django 2.0 on 2018-01-12 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-in_reply_to__created', '-last_modified', '-created')},
        ),
        migrations.AlterField(
            model_name='post',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='posts.Post'),
        ),
    ]
