# Generated by Django 2.0 on 2017-12-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171228_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': 'topics'},
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='posts',
            field=models.ManyToManyField(blank=True, editable=False, related_name='topics', to='posts.Post'),
        ),
    ]
