# Generated by Django 2.0 on 2017-12-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171228_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'ordering': ('parent', '-last_modified', '-created'),
                'verbose_name_plural': 'categories'
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-last_modified', '-created')},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={
                'ordering': ('-last_modified', '-created'),
                'verbose_name_plural': 'topics'
            },
        ),
    ]
