# Generated by Django 2.0 on 2017-12-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171226_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(blank=True, editable=False, related_name='categories', to='posts.Post'),
        ),
    ]
